title: CCDL Training
training_title: 2022 September Single Cell Training
# The name of the repository (e.g., 2020-may-training)
# We use training-specific-template to help with development
repository: 2022-september-training
# Full URL to the repository
# Again, using training-specific-template to aid in development
repository_url: https://github.com/AlexsLemonade/2022-september-training
start_date: 2022-09-19
end_date: 2022-09-23
# Specific release in AlexsLemonade/training-modules
# We use master to make development easier
release_tag: master
# The Docker user will almost always be ccdl, which is why this is here
docker_user: ccdl
docker_repo: training_rnaseq
docker_tag: 2022-september
# These are for loading Docker images from a file; only relevant for in-person
docker_targz: ccdl_docker_image.tar.gz
docker_tar: ccdl_docker_image.tar


# Theme and theme options
theme: minima
# Pages to appear in site header.
header_home:
  workshop/HOME.md
header_pages:
  # Note that when first cloned, the `workshop` directory will not exist,
  # as described at https://github.com/AlexsLemonade/training-specific-template#customizing-the-new-repository-for-an-individual-training-workshop
  - workshop/SCHEDULE.md
  - workshop/workshop-structure.md
  - workshop/workshop-materials.md
  - workshop/resources-for-consultation-sessions.md
  - working-with-your-data/working-with-your-own-data.md
  - workshop/posting-errors-guidelines.md
author: Childhood Cancer Data Lab
email: training@ccdatalab.org
twitter_username: CancerDataLab
github_username:  AlexsLemonade
